### ISSUE TITLE
migrate rule DetectedVariants

### ISSUE THREAD

**Issue by pyrevo** [genomic-medicine-sweden/pgx#28]
rule that will be converted:

```
rule DetectedVariants:
    """ Get variants with target rsIDs """
    params:
        target_bed        = load_local(config["table_data"]["target_rsid"]),
        hidden_haplotypes = load_local(config["table_data"]["hidden_haplotypes"]),
        script_location   = config["run_location"]
    input:
        vcf = "work/{seqID}/Results/Haplotypecaller/filtered/annotated/{sample}_{seqID}.vcf"
    output:
        csv = "work/{seqID}/Results/Report/detected_variants/{sample}_{seqID}.csv"
    singularity:
        config["singularities"]["get_target"]
    shell:
        """
        python3 {params.script_location}/src/Summary/get_target_variants.py \
            --target_bed {params.target_bed} \
            --vcf {input.vcf} \
            --output {output.csv} 
        """
```

- [x] create snakemake rule
- [ ] write unit tests for get_target_variants.py

## Other
Please follow [hydra-genetics guidelines](https://github.com/orgs/genomic-medicine-sweden/projects/3/views/1#:~:text=Please%20follow%20hydra%2Dgenetics%20guidelines)

**Comment by pyrevo** [comment]
ERROR in get_target_variants.py:

```
Traceback (most recent call last):
  File "/home/massi/Documents/GMS/hydra_genetics/hydra_test/hydra_0.15.0/pgx/test.py", line 158, in <module>
    main()
  File "/home/massi/Documents/GMS/hydra_genetics/hydra_test/hydra_0.15.0/pgx/test.py", line 153, in main
    var_collect = VariantQCCollection(bed_f, vcf_f)
  File "/home/massi/Documents/GMS/hydra_genetics/hydra_test/hydra_0.15.0/pgx/test.py", line 112, in __init__
    self.vcf = VCF(vcf_filename)
  File "/home/massi/Documents/GMS/hydra_genetics/hydra_test/hydra_0.15.0/pgx/test.py", line 62, in __init__
    self.read_vcf(filename)
  File "/home/massi/Documents/GMS/hydra_genetics/hydra_test/hydra_0.15.0/pgx/test.py", line 87, in read_vcf
    format_columns = self.data.FORMAT[max_len_idx].split(":")
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/hydra-genetics_0.15.0/lib/python3.10/site-packages/pandas/core/series.py", line 945, in __getitem__
    key = com.apply_if_callable(key, self)
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/hydra-genetics_0.15.0/lib/python3.10/site-packages/pandas/core/common.py", line 358, in apply_if_callable
    return maybe_callable(obj, **kwargs)
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/hydra-genetics_0.15.0/lib/python3.10/site-packages/pandas/core/series.py", line 2404, in idxmax
    i = self.argmax(axis, skipna, *args, **kwargs)
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/hydra-genetics_0.15.0/lib/python3.10/site-packages/pandas/core/base.py", line 646, in argmax
    nv.validate_minmax_axis(axis)
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/hydra-genetics_0.15.0/lib/python3.10/site-packages/pandas/compat/numpy/function.py", line 408, in validate_minmax_axis
    if axis >= ndim or (axis < 0 and ndim + axis < 0):
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/hydra-genetics_0.15.0/lib/python3.10/site-packages/pandas/core/ops/common.py", line 70, in new_method
    return method(self, other)
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/hydra-genetics_0.15.0/lib/python3.10/site-packages/pandas/core/arraylike.py", line 60, in __ge__
    return self._cmp_method(other, operator.ge)
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/hydra-genetics_0.15.0/lib/python3.10/site-packages/pandas/core/series.py", line 5623, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/hydra-genetics_0.15.0/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 283, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/hydra-genetics_0.15.0/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 73, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
  File "pandas/_libs/ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>=' not supported between instances of 'str' and 'int'
```

Solution:
```
#max_len_idx = self.data.FORMAT.str.len().idxmax
#format_columns = self.data.FORMAT[max_len_idx].split(":")
format_columns=self.data.FORMAT[0].split(":")
```

Comment:
It should work since if vcf is not empty you should have at least the first entry. But to be tested further.

**Comment by pyrevo** [comment]
It looks like this bugfix is working well so I will close this issue.
