### ISSUE TITLE
migrate rule AppendIDtoGDF

### ISSUE THREAD

**Issue by pyrevo** [genomic-medicine-sweden/pgx#39]
rule that will be converted: 
```
rule AppendIDtoGDF:
    """ Add variant id to appropriate location in gdf """
    params:
        target_bed = load_local(config["table_data"]["target_rsid"]),
        script_location   = config["run_location"]
    input:
        gdf = "work/{seqID}/Results/Report/coverage/{sample}_{seqID}_depth_at_missing.gdf"
    output:
        gdf = "work/{seqID}/Results/Report/coverage/{sample}_{seqID}_depth_at_missing_annotated.gdf"
    singularity:
        config["singularities"]["get_target"]
    shell:
         """
         python3 {params.script_location}/src/Summary/append_rsid_to_gdf.py \
            --input_gdf={input.gdf} \
            --target_bed={params.target_bed} \
            --output_file={output.gdf}
         """
```

## scripts:
- [x] move  [append_rsid_to_gdf.py ](https://github.com/JoelAAs/pgx_module/blob/master/src/Summary/append_rsid_to_gdf.py)
- [ ]  write unit tests for append_rsid_to_gdf.py
- [x]  update requirements with dependencies 

script should be located under workflow/scripts and probably utilize  the [snakemake  object](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#external-scripts) to fetch parameters, instead of argparse 

## snakemake rules
- [x]  create snakemake rule that uses the script

### config
extra entries:
- [x] target_bed

## Other
Please follow [hydra-genetics guidelines](https://docs.google.com/document/d/1l2v1ItZBTDaI72vQPZcaQzxwVUao78XzIJvGASAAD9E/edit?usp=sharing)

**Comment by pyrevo** [comment]
Failing to import module from get_targets_variants.py only for the dry run:

`snakemake -s ../../workflow/Snakefile -j1 --use-singularity --configfile config/config.yaml -p
`
```
[Thu Jan 26 11:00:58 2023]
Job 15: append_id_to_gdf: add variant id to appropriate location in pgx/depth_of_coverage/depth_of_targets/HD832_T_chr6.depth_at_missing.gdf
Reason: Missing output files: pgx/append_id_to_gdf/HD832_T_chr6.depth_at_missing_annotated.gdf

python /home/massi/Documents/GMS/pgx/.tests/integration/.snakemake/scripts/tmp_66ms2e2.append_rsid_to_gdf.py
Activating singularity image /home/massi/Documents/GMS/pgx/.tests/integration/.snakemake/singularity/a117c28d184e95a1374cb6ce306752cc.simg
INFO:    Converting SIF file to temporary sandbox...
Traceback (most recent call last):
  File "/home/massi/Documents/GMS/pgx/.tests/integration/.snakemake/scripts/tmp_66ms2e2.append_rsid_to_gdf.py", line 5, in <module>
    from get_target_variants import GDF
ModuleNotFoundError: No module named 'get_target_variants'
INFO:    Cleaning up image...
[Thu Jan 26 11:01:01 2023]
Error in rule append_id_to_gdf:
    jobid: 15
    output: pgx/append_id_to_gdf/HD832_T_chr6.depth_at_missing_annotated.gdf
    log: pgx/append_id_to_gdf/HD832_T_chr6.output.log (check log file(s) for error message)
    conda-env: /home/massi/Documents/GMS/pgx/.tests/integration/.snakemake/conda/b4595e2de5392acd6963419a6ab0e276_

RuleException:
CalledProcessErrorin line 37 of /home/massi/Documents/GMS/pgx/workflow/rules/append_id_to_gdf.smk:
Command ' singularity  exec --home /home/massi/Documents/GMS/pgx/.tests/integration  --bind /opt/sw/bioinfo-tools/sources/anaconda3/envs/hydra-genetics_0.15.0/lib/python3.10/site-packages:/mnt/snakemake /home/massi/Documents/GMS/pgx/.tests/integration/.snakemake/singularity/a117c28d184e95a1374cb6ce306752cc.simg bash -c 'set -euo pipefail;  python /home/massi/Documents/GMS/pgx/.tests/integration/.snakemake/scripts/tmp_66ms2e2.append_rsid_to_gdf.py'' returned non-zero exit status 1.
  File "/home/massi/Documents/GMS/pgx/workflow/rules/append_id_to_gdf.smk", line 37, in __rule_append_id_to_gdf
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/hydra-genetics_0.15.0/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

Solutions tested but not working:
[snakemake auxiliary source files](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#accessing-auxiliary-source-files)
[__init__.py](https://stackoverflow.com/questions/4383571/importing-files-from-different-folder)

Dirty solution:
Include redundant GDF class into append_rsid_to_gdf.py
